# Generated by Django 5.1.1 on 2024-09-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffeproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffekind', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('coffename', models.CharField(blank=True, max_length=100)),
                ('coffetype', models.CharField(blank=True, max_length=100)),
                ('coffephoto', models.ImageField(blank=True, default='coffephotoes/', null=True, upload_to='coffephotoes/')),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coffetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('fullnames', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('profilephoto', models.ImageField(blank=True, default='profilepicture/', null=True, upload_to='profilepicture/')),
                ('membership', models.CharField(blank=True, max_length=100)),
                ('balance', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(blank=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('productname', models.CharField(blank=True, null=True)),
                ('producttype', models.CharField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('price', models.FloatField(blank=True, null=True)),
                ('coffephoto', models.ImageField(blank=True, default='ordersphoto/', null=True, upload_to='ordersphoto/')),
              
                ('time', models.CharField(blank=True, max_length=100)),
                ('date', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
