# Generated by Django 5.1.1 on 2024-10-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_alter_orders_coffephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(blank=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('productname', models.CharField(blank=True, null=True)),
                ('producttype', models.CharField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('coffephoto', models.CharField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=100)),
                ('date', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
