# Generated by Django 5.1.1 on 2024-10-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_alter_history_orderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notitype', models.CharField(blank=True)),
                ('notiid', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('notiphoto', models.CharField(blank=True, null=True)),
                ('date', models.CharField(blank=True, null=True)),
                ('time', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
